<template>
  <div>
    <chat-container/>
  </div>
</template>

<script>
import ChatContainer from '@/components/support/ChatContainer';
import {EventBus} from '../event-bus.js';
import util from '../util';

EventBus.$on('vue-initialized-support', ({ chatEngine, store }) => {
  // Channel where each private chat's metadata is stored, so the support agent
  // can see their chat history in the UI
  // don't expose this to clients besides support user client
  const privateChatKeyChannel = 'private-chat-keys-a1';

  const me = {
    name: 'support',
    uuid: 'support',
  };

  chatEngine.connect(me.uuid, me);

  document.addEventListener('beforeunload', function() {
    chatEngine.disconnect();
  });

  chatEngine.on('$.ready', function(data) {
    // store my new user as `me`
    let me = data.me;
    store.commit('setMe', {me});
    // when a user comes online
    chatEngine.on('$.online.join', (data) => {
      let time = new Date();
      let key = data.user.state.uuid;
      let name = data.user.state.name;

      if (store.state.chats[key] || key === 'support') {
        return;
      }

      let newChat = {};

      newChat.chatKey = newChat.uuid = key;
      newChat.time = time.getTime();
      newChat.name = name;

      // Make the new 1:1 private Chat
      util.newChatEngineChat(
        store,
        chatEngine,
        newChat,
        true,
      );
    });

    getCustomerChats().then((chats) => {
      chats.forEach((chat) => {
        chat = chat.entry;
        let key = chat.uuid;

        if (store.state.chats[key] || key === 'support') {
          return;
        }

        // Add the chat key to the Chat object for Vue UI use
        chat.chatKey = key;

        // Make the new 1:1 private Chat
        const myChat = util.newChatEngineChat(
          store,
          chatEngine,
          chat,
          true,
        );

        myChat.on('$.connected', () => {
          store.commit('setCurrentChat', {
            chatKey: key,
          });

          store.commit('setChatEngineReady', {});

          store.state.chats[key].search({
            event: 'message',
            limit: 100,
            reverse: true
          });
        });
      });
    });
  });

  function getCustomerChats(count) {
    return new Promise((resolve, reject) => {
      count = count || 100;
      let oldAuthKey = chatEngine.pubnub.getAuthKey();
      chatEngine.pubnub.setAuthKey('support-user-auth-key');
      chatEngine.pubnub.history(
        {
          channel: privateChatKeyChannel,
          reverse: true,
          count: count,
        },
        function (status, response) {
          if (status.statusCode === 200) {
            resolve(response.messages);
          } else {
            reject(status);
          }
        }
      );
      chatEngine.pubnub.setAuthKey(oldAuthKey);
    });
  }
});

export default {
  name: 'Support',
  components: {
    ChatContainer,
  },
};

</script>

<style>
#app {
  font-family: Helvetica;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #454d54;
  margin-top: 60px;
}

/* Loading Ripple Animation */
/* Generated by loading.io */
@keyframes lds-ripple {
  0% {
    top: 96px;
    left: 96px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 8px;
    left: 8px;
    width: 176px;
    height: 176px;
    opacity: 0;
  }
}
@-webkit-keyframes lds-ripple {
  0% {
    top: 96px;
    left: 96px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 8px;
    left: 8px;
    width: 176px;
    height: 176px;
    opacity: 0;
  }
}
.lds-ripple {
  position: relative;
}
.lds-ripple div {
  box-sizing: content-box;
  position: absolute;
  border-width: 4px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  -webkit-animation: lds-ripple 2.6s cubic-bezier(0, 0.2, 0.8, 1) infinite;
  animation: lds-ripple 2.6s cubic-bezier(0, 0.2, 0.8, 1) infinite;
}
.lds-ripple div:nth-child(1) {
  border-color: #000000;
}
.lds-ripple div:nth-child(2) {
  border-color: rgba(0%,0%,0%,0.675);
  -webkit-animation-delay: -1.3s;
  animation-delay: -1.3s;
}
.lds-ripple {
  width: 36px !important;
  height: 36px !important;
  -webkit-transform: translate(-18px, -18px) scale(0.18) translate(18px, 18px);
  transform: translate(-18px, -18px) scale(0.18) translate(18px, 18px);
}
</style>
